spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info,bus-refresh

test:
  username: config-client1/aaa-test
  password: config-client1/123-test

foo: config-client1/foo-aaa-test