test:
  username: test1_1
  password: 123test_1

foo: test_foo

spring:
  redis:
    host: 192.168.0.108
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    timeout: 5000
    database: 2
    password: root
